USE [master]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[file2](
	[business_id] [varchar](50) NULL,
	[full_address] [varchar](max) NULL,
	[open] [varchar](max) NULL,
	[categories] [varchar](max) NULL,
	[city] [varchar](max) NULL,
	[review_count] [varchar](max) NULL,
	[name] [varchar](max) NULL,
	[neighborhoods] [varchar](max) NULL,
	[longitude] [varchar](max) NULL,
	[state] [varchar](50) NULL,
	[stars] [varchar](50) NULL,
	[latitude] [varchar](max) NULL,
	[type] [varchar](50) NULL,
	[hours Friday close] [varchar](50) NULL,
	[hours Friday open] [varchar](50) NULL,
	[hours Tuesday close] [varchar](50) NULL,
	[hours Tuesday open] [varchar](50) NULL,
	[hours Thursday close] [varchar](50) NULL,
	[hours Thursday open] [varchar](50) NULL,
	[hours Wednesday close] [varchar](50) NULL,
	[hours Wednesday open] [varchar](50) NULL,
	[hours Monday close] [varchar](50) NULL,
	[hours Monday open] [varchar](50) NULL,
	[attributes Take-out] [varchar](50) NULL,
	[attributes Drive-Thru] [varchar](50) NULL,
	[attributes Good For dessert] [varchar](50) NULL,
	[attributes Good For latenight] [varchar](50) NULL,
	[attributes Good For lunch] [varchar](50) NULL,
	[attributes Good For dinner] [varchar](50) NULL,
	[attributes Good For brunch] [varchar](50) NULL,
	[attributes Good For breakfast] [varchar](50) NULL,
	[attributes Caters] [varchar](50) NULL,
	[attributes Noise Level] [varchar](50) NULL,
	[attributes Takes Reservations] [varchar](50) NULL,
	[attributes Delivery] [varchar](50) NULL,
	[attributes Ambience romantic] [varchar](50) NULL,
	[attributes Ambience intimate] [varchar](50) NULL,
	[attributes Ambience classy] [varchar](50) NULL,
	[attributes Ambience hipster] [varchar](50) NULL,
	[attributes Ambience divey] [varchar](50) NULL,
	[attributes Ambience touristy] [varchar](50) NULL,
	[attributes Ambience trendy] [varchar](50) NULL,
	[attributes Ambience upscale] [varchar](50) NULL,
	[attributes Ambience casual] [varchar](50) NULL,
	[attributes Parking garage] [varchar](50) NULL,
	[attributes Parking street] [varchar](50) NULL,
	[attributes Parking validated] [varchar](50) NULL,
	[attributes Parking lot] [varchar](50) NULL,
	[attributes Parking valet] [varchar](50) NULL,
	[attributes Has TV] [varchar](50) NULL,
	[attributes Outdoor Seating] [varchar](50) NULL,
	[attributes Attire] [varchar](50) NULL,
	[attributes Alcohol] [varchar](50) NULL,
	[attributes Waiter Service] [varchar](50) NULL,
	[attributes Accepts Credit Cards] [varchar](50) NULL,
	[attributes Good for Kids] [varchar](50) NULL,
	[attributes Good For Groups] [varchar](50) NULL,
	[attributes Price Range] [varchar](50) NULL,
	[attributes Happy Hour] [varchar](50) NULL,
	[hours Sunday close] [varchar](50) NULL,
	[hours Sunday open] [varchar](50) NULL,
	[hours Saturday close] [varchar](50) NULL,
	[hours Saturday open] [varchar](50) NULL,
	[attributes Good For Dancing] [varchar](50) NULL,
	[attributes Coat Check] [varchar](50) NULL,
	[attributes Smoking] [varchar](50) NULL,
	[attributes Wi-Fi] [varchar](50) NULL,
	[attributes Music dj] [varchar](50) NULL,
	[attributes Wheelchair Accessible] [varchar](50) NULL,
	[attributes Dogs Allowed] [varchar](50) NULL,
	[attributes BYOB] [varchar](50) NULL,
	[attributes Corkage] [varchar](50) NULL,
	[attributes BYOB Corkage] [varchar](50) NULL,
	[attributes Order at Counter] [varchar](50) NULL,
	[attributes Music background_music] [varchar](50) NULL,
	[attributes Music jukebox] [varchar](50) NULL,
	[attributes Music live] [varchar](50) NULL,
	[attributes Music video] [varchar](50) NULL,
	[attributes Music karaoke] [varchar](50) NULL,
	[attributes By Appointment Only] [varchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

BULK INSERT food FROM 'C:\Users\DG-MS10\Desktop\git_projects\BIg_Data-master\BIg_Data\project 2\file.tsv' WITH (FIELDTERMINATOR = '\t', ROWTERMINATOR = '|');
